### ISSUE TITLE
Country API down

### ISSUE THREAD

**Issue by soracoder** [fabian7593/CountryAPI#5]
It seems like the API has some problem because the response to:
[http://countryapi.gear.host/v1/Country/getCountries](http://countryapi.gear.host/v1/Country/getCountries)

is:
`{"IsSuccess":false,"UserMessage":"An error occurred, please contact the administrator.","TechnicalMessage":"A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: SSL Provider, error: 0 - The wait operation timed out.)","TotalCount":null,"Response":null}`

Maybe some SSL problem ?

**Comment by fabian7593** [comment]
Yes is a possibillity, that's why I put in the documentation.

**Suggestion: GearHost is a free hosting web apps, and has a limit of request by hour, I recommended download the repository and made your own server, and use this only for tests. If you like the repository, my work, and you want that this works ever in the current host or other, please Donate, I will thanks you and the developers community too.**
